import {test} from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {once} from 'node:events';
import {createFormService,readServiceConfig} from './server.mjs';import {MetadataStore} from './store.mjs';
const config={apiKey:'synthetic-test-only',from:'support@o-ibs.co.za',to:'support@o-ibs.co.za',secret:'synthetic-testing-secret-at-least-32-characters',origin:'https://o-ibs.co.za'};
const sample={name:'Demo Owner',business:'Demo Company',email:'owner@example.invalid',businessType:'Retail',employees:'2–5',plan:'Complete',areas:['Stock/inventory'],message:'Synthetic test only.',privacy:true,website:'',noticeVersion:'2026-10-07'};
async function fixture(options={}){let now=Date.now(),calls=[];const store=new MetadataStore();const instance=createFormService(config,{store,clock:()=>now,providerFetch:async(url,request)=>{calls.push({url,request});return options.provider?options.provider(url,request):new Response(JSON.stringify({id:'synthetic-provider-id'}),{status:200});}});instance.server.listen(0,'127.0.0.1');await once(instance.server,'listening');const url='http://127.0.0.1:'+instance.server.address().port;return {calls,store,url,async token(){const r=await fetch(url+'/api/form-token',{headers:{Origin:config.origin}});const data=await r.json();now+=3001;return data.token;},advance(ms){now+=ms;},async post(data,route='early-access',headers={}){return fetch(url+'/api/'+route,{method:'POST',headers:{Origin:config.origin,'Content-Type':'application/json',...headers},body:JSON.stringify(data)});},async close(){await new Promise(r=>instance.server.close(r));store.close();}};}
async function payload(f,extra={}){return {...sample,submissionId:crypto.randomUUID(),token:await f.token(),...extra};}
test('strict server input/method/CORS/body validation; no attachments or injection into email headers',async()=>{const f=await fixture();try{const good=await payload(f);for(const extra of [{email:'x@example.invalid\r\nBcc: x@y.invalid'},{business:'Demo\nBcc: x@y.invalid'},{name:{text:'owner'}},{message:'x'.repeat(1001)},{privacy:false},{areas:['unknown']},{areas:['Banking','Banking']},{attachments:[]},{phone:'123'},{noticeVersion:'wrong'},{website:'spam'},{token:'forged'},{submissionId:'bad'}])assert.equal((await f.post({...good,...extra})).status,422);
 for(const method of ['GET','PUT','PATCH','DELETE'])assert.equal((await fetch(f.url+'/api/contact',{method,headers:{Origin:config.origin}})).status,405);
 assert.equal((await f.post(good,'early-access',{Origin:'https://attacker.invalid'})).status,403);assert.equal((await f.post(good,'early-access',{'Content-Type':'multipart/form-data'})).status,415);
 assert.equal((await fetch(f.url+'/api/contact',{method:'POST',headers:{Origin:config.origin,'Content-Type':'application/json'},body:'{broken'})).status,400);
 assert.equal((await f.post({...good,message:'x'.repeat(17000)})).status,413);assert.equal(f.calls.length,0);
 assert.equal((await fetch(f.url+'/.env')).status,404);const preflight=await fetch(f.url+'/api/contact',{method:'OPTIONS',headers:{Origin:config.origin,'Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'content-type'}});assert.equal(preflight.status,204);assert.equal(preflight.headers.get('access-control-allow-origin'),config.origin);
}finally{await f.close();}});
test('escaped notifications and provider duplicate protection survive restarts and independent instances',async()=>{
 const sent=new Map();let deliveries=0,loseAcknowledgment=true;
 const provider=async(_url,request)=>{const key=request.headers['Idempotency-Key'];if(sent.has(key))assert.equal(sent.get(key),request.body);else{sent.set(key,request.body);deliveries++;}if(loseAcknowledgment){loseAcknowledgment=false;throw Error('Response lost after provider accepted');}return new Response(JSON.stringify({id:'synthetic-id'}));};
 let f=await fixture({provider});let data;
 try{data=await payload(f,{business:'<script>Demo</script>',message:'<img src=x onerror=alert(1)>'});assert.equal((await f.post(data)).status,503);const email=JSON.parse(f.calls[0].request.body);assert(email.html.includes('&lt;script&gt;'));assert(!email.html.includes('<script>'));assert.deepEqual(email.to,[config.to]);assert.equal(email.reply_to,data.email);assert(!email.attachments);}finally{await f.close();}
 f=await fixture({provider});const other=await fixture({provider});try{
 const retry={...data,token:await f.token()};assert.equal((await (await f.post(retry)).json()).accepted,true);assert.equal(deliveries,1);
 assert.equal((await (await f.post(retry)).json()).accepted,true);assert.equal(f.calls.length,1);assert.equal((await f.post({...retry,message:'different'})).status,409);
 const duplicate={...data,submissionId:crypto.randomUUID(),token:await other.token()};assert.equal((await (await other.post(duplicate)).json()).accepted,true);assert.equal(deliveries,1);
 assert.equal(f.calls[0].request.body,other.calls[0].request.body);assert.equal(f.calls[0].request.headers['Idempotency-Key'],other.calls[0].request.headers['Idempotency-Key']);
 }finally{await f.close();await other.close();}
});
test('provider errors/timeouts/invalid acknowledgment never succeed; retries reuse provider idempotency/body',async()=>{for(const outcome of ['error','conflict','throw','missing']){let fail=true;const f=await fixture({provider:async()=>{if(fail){if(outcome==='throw')throw Error('synthetic network error including secret');return new Response(JSON.stringify(outcome==='missing'?{}:{error:'private provider message'}),{status:outcome==='error'?500:outcome==='conflict'?409:200});}return new Response(JSON.stringify({id:'synthetic-id'}));}});try{const data=await payload(f);const first=await f.post(data);assert.equal(first.status,503);const result=await first.json();assert.equal(result.accepted,false);assert(!JSON.stringify(result).includes('private provider'));fail=false;assert.equal((await (await f.post(data)).json()).accepted,true);assert.equal(f.calls[0].request.headers['Idempotency-Key'],f.calls[1].request.headers['Idempotency-Key']);assert.equal(f.calls[0].request.body,f.calls[1].request.body);}finally{await f.close();}}});
test('parallel duplicate presses produce one provider call; process rate limits and token timing blocks simple bots',async()=>{let release;const pending=new Promise(r=>release=r);const f=await fixture({provider:async()=>{await pending;return new Response(JSON.stringify({id:'synthetic-id'}));}});try{const tokenResponse=await fetch(f.url+'/api/form-token',{headers:{Origin:config.origin}});const fresh=(await tokenResponse.json()).token;assert.equal((await f.post({...sample,token:fresh,submissionId:crypto.randomUUID()})).status,422);const data=await payload(f);const first=f.post(data);await new Promise(r=>setTimeout(r,30));assert.equal((await f.post(data)).status,409);release();assert.equal((await (await first).json()).accepted,true);assert.equal(f.calls.length,1);for(let i=0;i<5;i++){const r=await f.post(await payload(f,{message:'Attempt '+i}));if(i<4)assert.equal(r.status,200);else assert.equal(r.status,429);}f.advance(31*60_000);assert.equal((await f.post({...data,submissionId:crypto.randomUUID()})).status,422);}finally{release();await f.close();}});
test('Contact uses same isolated delivery; startup fails closed without credentials',async()=>{const f=await fixture();try{const data={name:'Demo Owner',business:'Demo Company',email:'owner@example.invalid',topic:'General enquiry',message:'Synthetic contact.',website:'',noticeVersion:'2026-10-07',submissionId:crypto.randomUUID(),token:await f.token()};assert.equal((await (await f.post(data,'contact')).json()).accepted,true);assert(JSON.parse(f.calls[0].request.body).subject.startsWith('New O-IBS Contact Enquiry'));assert.throws(()=>readServiceConfig({}));assert.equal(readServiceConfig({RESEND_API_KEY:'test',MAIL_FROM:config.from,MAIL_TO:config.to,FORMS_HMAC_SECRET:config.secret,FORMS_ALLOWED_ORIGIN:config.origin}).origin,config.origin);assert.throws(()=>readServiceConfig({RESEND_API_KEY:'test',MAIL_FROM:config.from,MAIL_TO:config.to,FORMS_HMAC_SECRET:config.secret,FORMS_ALLOWED_ORIGIN:'https://staging.o-ibs.co.za',FORMS_DATA_DIR:'/var/data'}));}finally{await f.close();}});
