export const company={name:'O-IBS',registration:'2026/798906/07',country:'South Africa',supportEmail:'support@o-ibs.co.za',vatRegistered:false};
export const monthlyPrices={BASIC:190,BUSINESS:450,COMPLETE:650};
// Add only owner-approved official profiles. Empty means no social links are published.
export const officialSocialProfiles=[];
export function validateSocialProfiles(profiles){for(const {name,url} of profiles){const parsed=new URL(url);if(!name||parsed.protocol!=='https:'||parsed.username||parsed.password||!['www.linkedin.com','linkedin.com','www.facebook.com','facebook.com','www.instagram.com','instagram.com'].includes(parsed.hostname)||parsed.pathname==='/')throw Error('Only approved official HTTPS social profile links may be published');}return profiles;}
export const supportLink=()=>`<a class="text-link" href="mailto:${company.supportEmail}">${company.supportEmail}</a>`;
export const companyIdentity=()=>`<p class="company-identity"><strong>${company.name}</strong><br>Registration number: ${company.registration}<br>${company.country}</p>`;
// Populate only after owner approval and professional review, never by detecting an unreviewed file.
// Example: {source:'src/assets/legal/approved-paia-manual.pdf',updated:'YYYY-MM-DD'}.
export const approvedPaiaManual=null;
export function structuredData(origin,description){return {'@context':'https://schema.org','@graph':[
 {'@type':'Organization','@id':origin+'/#organization',name:company.name,legalName:company.name,url:origin,logo:origin+'/assets/icon-512.png',identifier:{'@type':'PropertyValue',propertyID:'South African enterprise registration number',value:company.registration},areaServed:{'@type':'Country',name:company.country}},
 {'@type':'WebSite','@id':origin+'/#website',name:company.name,url:origin,description,inLanguage:'en-ZA',publisher:{'@id':origin+'/#organization'}}
 ]};}
export function paiaPage(pageHero){return `${pageHero('PAIA / Access to information','Access to information.<br>A clear next step.','PAIA is South Africa’s Promotion of Access to Information Act. It explains how people may request records to exercise or protect a right.')}<section class="section"><div class="wrap longcopy">${companyIdentity()}<div class="notice"><strong>${approvedPaiaManual?'Approved manual available below.':'Final PAIA manual not yet available.'}</strong><p>${approvedPaiaManual?'Use the reviewed document for the request process and approved contact details.':'This status page is not a PAIA manual. The final document and approved Information Officer contact details require owner confirmation and professional legal review.'}</p></div><h2>The short version</h2><p>The PAIA manual will explain the kinds of records held by O-IBS, the relevant request process and where to send a request. Access is subject to the Act; a request does not automatically entitle someone to another business’s confidential records.</p><h2>PAIA manual</h2>${approvedPaiaManual?'<p><a class="btn gold" href="/assets/legal/o-ibs-paia-manual.pdf">Download the approved PAIA manual (PDF)</a></p>':'<p>No download is offered until a final approved manual has been supplied. We will link it here once ready.</p>'}<h2>Information Officer and request channel</h2><p>O-IBS does not currently have a confirmed/registered Information Officer. The formal records-request procedure still requires approval. General questions can be emailed to ${supportLink()}; this is not a published Information Officer appointment. The website forms cannot submit a PAIA request.</p><h2>Official guidance</h2><p>See the <a class="text-link" href="https://inforegulator.org.za/paia/">Information Regulator’s PAIA guides and forms</a> for the official process. Read the <a class="text-link" href="/privacy">Privacy Policy draft</a> and <a class="text-link" href="/popia">POPIA &amp; Privacy</a> for personal-information topics.</p></div></section>`;}
