export const faqItems=[
 ['What does O-IBS do?','O-IBS means Optimised Intelligent Business System. It brings quotes, invoices, customers, suppliers, purchases, stock, banking and accounting together, with Bizzy to help you find information and prepare work. Available tools depend on your plan and closed-beta workspace.'],
 ['Who is O-IBS for?','South African small-business owners and teams, including service businesses, retailers, wholesalers and trade businesses. Basic focuses on everyday sales and expenses; Business adds deeper financial workflows; Complete adds products and stock.'],
 ['Do I need accounting knowledge?','You can start with familiar tasks: quoting, invoicing, recording payments and organising expenses. Plain-English explanations help you understand the records. Your bookkeeper or accountant should still review accounting setup, adjustments and tax treatment.'],
 ['What can Bizzy help with?','Ask everyday questions about your business, find records and prepare work within the tools enabled for your workspace. Check answers against your records. Actions that create or change financial or stock records are prepared for your review and explicit confirmation; a suggestion is not a completed action.'],
 ['Can I create quotes and invoices?','Professional quotes and invoices, customer payments and business expenses form part of Basic and the larger plans. Check the customer, amounts and tax treatment before confirming a document.'],
 ['How does VAT work?','VAT means value-added tax. O-IBS includes tools for recording VAT on sales and purchases where available in your workspace. Your accountant should check the correct settings and tax treatment. O-IBS itself is not currently VAT registered, so no VAT is presently charged on the published monthly plan prices. Tax filing or automatic submission to SARS is not promised.'],
 ['Which plan includes stock?','Complete covers products, stock quantities, purchase orders and recording stock when it arrives. It helps you see what is available, reserved or running low and review the recorded value of stock.'],
 ['Can I manage suppliers and purchases?','Business includes money you still owe suppliers and more detailed financial reporting. Complete adds purchase orders and goods received for businesses buying and holding stock. Compare the plan guide and confirm the tools available for your invited workspace.'],
 ['Does O-IBS connect directly to my bank?','The described banking workflow uses imported or manually recorded statement transactions. Review suggested matches and confirm how they relate to your business records (bank reconciliation). A live bank feed is not promised, and recording a payment does not initiate a transfer.'],
 ['Can I import my existing accounting information?','Discuss your starting records with O-IBS before moving real data. Onboarding and import options depend on your business and will be reviewed during Early Access. Real historical accounting-data migration is not generally available and must wait until the separate security and data-protection checks for real customer data are completed. Any approved migration will be controlled and reviewed with the person responsible for your accounts.'],
 ['Can I upload documents or capture receipts?','O-IBS can scan or upload supported JPG, PNG and PDF receipts and supplier invoices, extract information and prepare it for review where document reading is configured. Expense receipt capture is available from Basic; supplier-invoice capture requires Business or Complete. Check the extracted details, amounts and VAT treatment. Extraction is not approval, VAT is not automatically claimable, and saving financial records requires review and confirmation. Not every document type is supported. Public Contact and Early Access forms do not accept attachments.'],
 ['How is my business information protected?','The application uses signed-in access, company membership and permissions to control access to records. Changes to financial or stock records require review and confirmation. These principles are not a security certification. Legal and privacy pages remain drafts; qualified review and the separate Production Security & Data Protection gate remain required before real customers and data.'],
 ['What are the monthly prices?','Basic is R190/month, Business R450/month and Complete R650/month. O-IBS is not currently registered for VAT; no VAT is presently charged. Public paid subscriptions are not open.'],
 ['Can I upgrade or downgrade?','Discuss a change with O-IBS during closed beta. Eligibility, timing and the handling of records that use features outside a new plan need review. Automatic switching, refunds and final cancellation terms are not promised here.'],
 ['What happens when I apply for Early Access?','O-IBS reviews your application. Applying does not guarantee acceptance, automatically create an account, start a subscription, take payment or give application access. Selected businesses receive an invitation after review. A receipt means the submission was accepted for processing, not that it was approved.'],
 ['How do I get support?','Email support@o-ibs.co.za for support and general questions. Existing invited users should use the sign-in address supplied to them. A response-time commitment or round-the-clock support is not promised.'],
 ['Why is O-IBS focused on South Africa?','The product is designed around South African small businesses, rand amounts (ZAR) and applicable VAT workflows. O-IBS stands for Optimised Intelligent Business System. Your business. One intelligent system.']
];
export function faqPage(pageHero){return `${pageHero('Questions, answered','A clearer starting point.<br>In everyday language.','Answers for South African small-business owners exploring O-IBS and controlled Early Access.')}<section class="section"><div class="wrap longcopy"><p class="micro">O-IBS is preparing for controlled Early Access / closed beta. Availability depends on your plan and invited workspace.</p><div class="meaning-grid faq-list">${faqItems.map(([q,a],i)=>`<details class="meaning" id="question-${i+1}"><summary><span>${q}</span></summary><p>${a}</p></details>`).join('')}</div><div class="actions"><a class="btn" href="/pricing">Compare the plans</a><a class="btn" href="/early-access">Understand Early Access</a><a class="text-link" href="/contact">Ask a question</a></div><p>For more detail, read the <a class="text-link" href="/security">security overview</a>, <a class="text-link" href="/ai-data">AI &amp; Data Use</a> and <a class="text-link" href="/privacy">Privacy Policy draft</a>.</p></div></section>`;}
export function featurePlanGuide(){return `<div class="grid"><article class="card"><div class="eyebrow">Basic · Business · Complete</div><h2 class="feature-title">Serve customers. Get paid.</h2><p>Keep customer details together. Prepare quotes and invoices, record payments and organise everyday business costs (expenses).</p><p>Basic includes customer balances, expense receipt capture and simple reports. Bizzy can help with everyday business questions.</p></article><article class="card"><div class="eyebrow">Business · Complete</div><h2 class="feature-title">Know where your money stands.</h2><p>See money customers still owe you (accounts receivable), money you owe suppliers (accounts payable), customer statements, credit notes and customer refunds.</p><p>Record supplier invoices and payments, capture supported supplier invoices for review, track assets and depreciation, match bank transactions to your records and explore detailed accounting and VAT reports.</p></article><article class="card"><div class="eyebrow">Complete</div><h2 class="feature-title">Follow your products and stock.</h2><p>Create purchase orders, record stock arriving from suppliers, and see available, reserved or low stock.</p><p>Review stock quantities and value, customer product returns and inventory reports. Bizzy can help answer questions about your stock.</p></article></div><p class="micro content-note">This guide follows the existing public plan comparison. The application’s entitlement rules determine access; confirm availability for your closed-beta workspace. Document assistance and specific formats depend on what is enabled.</p><div class="actions"><a class="btn" href="/pricing">Compare plans and prices</a><a class="text-link" href="/faq">Read common questions</a></div>`;}
