const drafts={
 privacy:{title:'Privacy Policy',description:'A structured privacy draft for review before public launch.',sections:[
 ['Scope and responsible party','This draft covers the public O-IBS marketing website and identifies topics that the separate application privacy notice must address. The responsible legal entity, registration details, Information Officer and approved privacy contact have not yet been supplied.'],
 ['Account and enquiry information','The final policy must describe account identifiers, contact details, company information and any enquiries processed through approved services. The current enquiry preview does not send or store the information entered. Do not include confidential financial information in a website enquiry.'],
 ['Business, customer and supplier data','Application records may include invoices, payments and customer or supplier details. The final notice must identify which information the application processes, why, the applicable lawful grounds and the respective responsibilities of O-IBS and its business users. The marketing website does not connect to the application database.'],
 ['Uploaded documents','The application notice must identify the handling of uploaded business documents, access boundaries, service providers, storage locations, retention and deletion. No upload function or document storage is provided by this public marketing site.'],
 ['AI-assisted functionality','The final notice must explain which information is supplied to AI services, for which purposes, who provides those services, and the applicable retention and transfer arrangements. Website Bizzy demonstrations use synthetic examples only. Review uncertain AI-assisted information; business-changing actions require human confirmation.'],
 ['Service providers and international transfers','Before publication, confirm the relevant hosting, email, storage and AI operators, their contractual roles and any cross-border processing arrangements. No list of providers or storage locations is asserted in this draft.'],
 ['Cookies and website analytics','This website currently uses no advertising trackers, third-party fonts or analytics scripts and does not use browser storage for enquiries. Hosting request logs depend on the selected provider and must be covered by the final policy. If optional analytics or non-essential cookies are introduced, review the privacy notice and appropriate consent handling first.'],
 ['Retention, deletion and safeguards','The final policy must set purpose-specific retention periods, deletion and backup handling, access controls and security arrangements. This draft does not promise an unverified retention period, encryption configuration or compliance certification.'],
 ['Rights and contact requests','The approved policy must explain how people request access, correction or deletion, raise objections where applicable and verify their identity proportionately. Approved request channels and response procedures are still required. Use the Information Regulator’s official guidance for South African privacy information.']
 ]},
 terms:{title:'Terms of Service',description:'A SaaS terms outline awaiting legal and commercial approval.',sections:[
 ['Parties and scope','The contracting entity and approved business details must be inserted before these terms can be offered for acceptance. This draft separates use of the public website from subscription and application services. It is not a final contract.'],
 ['Accounts and authorised access','The final terms must set out eligibility, account creation, invitations, verification, authorised users and the responsibilities of account holders. This website does not provide registration, authentication or access to business records.'],
 ['Subscriptions, trials and plan entitlements','Plan names and workflow descriptions are provisional. Final pricing, VAT treatment, billing periods, trial duration, renewal, cancellation and applicable limits require business approval and verification against the application’s entitlement definitions.'],
 ['Customer data and confidentiality','Review provisions about business data, appropriate access, permitted use, intellectual property, confidentiality and the relationship to the privacy notice. Define responsibilities for customer and supplier information without assuming an unreviewed legal allocation.'],
 ['AI assistance and user review','Describe the scope and limits of Bizzy and assisted document extraction. Users should review uncertain information and prepared actions. Financial and business-changing actions require confirmation before completion. Final wording must be consistent with released functionality.'],
 ['Acceptable use and security','The approved agreement should describe permitted use, restrictions, account security, suspension and incident reporting. No current support address or suspension process is invented here.'],
 ['Support, availability and changes','Confirm actual support channels, service availability arrangements, maintenance and how material changes are communicated. This draft makes no uptime, certification or support-response guarantee.'],
 ['Ending the service and data handling','Review cancellation, termination, export, deletion, backup retention and outstanding payment obligations. Verify these provisions against implemented workflows before publishing them.'],
 ['Liability, disputes and governing law','A qualified professional must finalise liability, warranties, dispute handling and governing law in the context of the contracting entity and the service. No attorney-approved agreement is represented by this outline.']
 ]},
 popia:{title:'POPIA Information',description:'Privacy and data-handling topics for South African users.',sections:[
 ['Purpose of this page','This draft explains the privacy topics O-IBS must finalise before launch. It does not assert POPIA compliance or replace the reviewed privacy notice. The responsible party and Information Officer details remain subject to confirmation.'],
 ['Clear purposes and limited information','The final documentation should explain what personal information is needed, why it is processed and how unnecessary collection is avoided. Information entered into the current website form is not submitted or stored.'],
 ['Business information and authorised access','Customer and supplier records can contain personal information. Final policies must clarify the roles of O-IBS and its business users, authorised access and appropriate operator arrangements. This public site has no access to application company records.'],
 ['Responsible assistance','Website Bizzy examples are fictional. The application’s AI data flows, providers, safeguards and retention need documented review. Human review remains important for uncertain information and actions that change business records.'],
 ['Access, correction and other requests','An approved privacy contact and request procedure are still required. The final process should explain identity verification and how access, correction, deletion or objections are handled where applicable.'],
 ['Questions and complaints','The Information Regulator provides official South African privacy information and a complaints process. O-IBS contact details must be approved before this draft becomes public release wording.']
 ]}
};
export function legalPage(kind,{pageHero,privacyEmail,escape}){const d=drafts[kind];return `${pageHero('Legal draft',d.title,d.description)}<section class="section"><div class="wrap longcopy"><div class="notice"><strong>DRAFT — requires professional legal review.</strong><p style="margin:8px 0 0">Not attorney-approved. Final wording and organisation details must be approved before broad public launch.</p></div>${d.sections.map(([title,text])=>`<section><h2>${title}</h2><p>${text}</p></section>`).join('')}<h2>Approved contact details</h2><p>${privacyEmail?`Privacy enquiries: <a class="text-link" href="mailto:${escape(privacyEmail)}">${escape(privacyEmail)}</a>`:'An operational O-IBS privacy address has not been configured. Approved contact details and a request process will be added before release.'}</p>${kind!=='terms'?'<p>Official resources: <a class="text-link" href="https://inforegulator.org.za/popia/">Information Regulator — POPIA</a> · <a class="text-link" href="https://inforegulator.org.za/complaints/">Complaints information</a></p>':''}<p class="micro">Draft for professional review · 6 October 2026</p></div></section>`;}
