import {companyIdentity,supportLink} from './company.mjs';
const drafts={
 privacy:{title:'Privacy Policy',description:'How O-IBS may handle personal information, with clear distinctions between this website and the separate application.',summary:'O-IBS uses information to support accounts and business workflows. This website does not access your company records; its examples are fictional and its enquiry preview does not send or store your details. Application records and AI requests may involve cloud providers. Provider arrangements, retention and privacy-request channels still need approval.',sections:[
 ['Who this notice is about','O-IBS is a South African enterprise, registration number 2026/798906/07. This draft covers the marketing website and describes the separate application’s information handling at a general level. Information Officer details and an approved privacy channel remain outstanding. The final notice must confirm the respective legal roles of O-IBS, customers and service providers.'],
 ['Information and why it is used','The application may process account identifiers, contact details, company settings and membership to provide access and support business workflows. Customer and supplier details, quotes, invoices, receipts, payments and other records support the business tasks you choose to carry out. Enter only information needed for those tasks. The final notice must confirm purposes and applicable lawful grounds.'],
 ['Enquiries and support','The Contact preview asks for your name, company, email, subject/category and message to help prepare an enquiry. It does not ask for a phone number. An enabled email submission service would use those details to handle your enquiry; online sending is enabled only after its backend has been configured and tested. When the forms are disabled, entries stay on the page and are not sent. When enabled, an isolated marketing service validates the details and sends an internal email through Resend for O-IBS to review and reply. Submissions do not create an account, company or subscription. Support requests are handled by email at support@o-ibs.co.za. The early-access application preview asks for name, business name/email/type, approximate employee count, areas of interest, plan and an optional message. The prepared service keeps only short-lived keyed hashes and abuse counters in memory, not application/enquiry text on disk. Duplicate-check metadata expires after 23 hours; rate counters expire within at most 24 hours. All memory metadata disappears when the service restarts. Resend retains email retry keys for 24 hours to prevent duplicate sending across restarts. The submitted details are included in the email handled by Resend and the receiving mailbox. Email-provider and mailbox retention/deletion arrangements still require confirmation in the reviewed notice before activation. Do not put confidential financial records in the preview.'],
 ['Uploaded business documents','Documents may contain personal or confidential information, such as customer names, line items and business instructions. Application access to stored documents is checked against company and feature permissions. This marketing site has no document upload. Storage locations, provider arrangements, retention and deletion must be documented for the released service.'],
 ['Bizzy and assisted document reading','Where enabled, AI may process your Bizzy request and details you include to interpret what you want to find or prepare. Assisted requisition reading may process document text, images or PDF pages to extract information for review. The AI & Data Use page explains scope and limitations. Website demonstrations are fictional and do not call AI services.'],
 ['Technical and security records','Hosting and application services may process request, error, access, session and security-event records to operate and protect the service. Records may include network identifiers and timestamps. The final policy must confirm fields, providers, access, purposes and retention. This website includes no advertising trackers, analytics scripts or third-party fonts.'],
 ['Cloud providers and international processing','Hosting, storage, email and AI services can process information on O-IBS’s behalf or under their applicable terms. The current AI implementation supports OpenAI when configured. The final notice must identify enabled providers, contractual roles, locations and any international-transfer arrangements. We do not claim that all information remains in South Africa.'],
 ['Keeping and deleting information','Retention should follow the information’s purpose, applicable record-keeping duties and approved agreements. Deletion requests may be subject to lawful retention and backup handling. No fixed retention period or automatic deletion promise is asserted here. An approved retention schedule and operational request process are required.'],
 ['Security principles','The application uses authenticated access, company permissions and document-access checks. Users should protect credentials and limit access to authorised people. Safeguards reduce risk but do not guarantee that incidents cannot occur. Operating controls and provider arrangements require review; this is not a security certification.'],
 ['Access, correction and other privacy requests','Access, correction, deletion or objections may be available depending on the circumstances and applicable law. Requests need an approved channel and proportionate identity checks. A customer company may need to handle requests relating to records it entered. The final notice must explain the responsible contact, restrictions and escalation route.'],
 ['Changes and questions','The reviewed policy should identify its effective date and how material changes are communicated. This draft is dated 7 October 2026 and is not an approved final policy. General privacy questions can be emailed to support@o-ibs.co.za. Formal privacy procedures and Information Officer governance remain outstanding.']
 ]},
 terms:{title:'Terms of Service',description:'Draft principles for O-IBS cloud business software, preparing for early access / closed beta.',summary:'O-IBS helps you organise business work. Protect your account, use authorised company access and check information before relying on it. Bizzy can make mistakes and important changes need approval. Monthly prices are approved; public paid access and final subscription terms are not yet available. This draft is not an agreement currently offered for paid subscription acceptance.',sections:[
 ['O-IBS and scope','O-IBS, registration number 2026/798906/07, South Africa, provides this marketing website and is preparing the separate application for early access / closed beta. The final agreement must confirm contracting details and distinguish website use, beta access and any later paid service.'],
 ['Eligibility and account responsibility','Use an account only when authorised and, when acting for a business, with authority to represent it. Keep account information accurate, protect credentials and manage access carefully. Final eligibility, invitation rules and responsibilities require approval before these terms are offered for acceptance.'],
 ['Company and user access','Company membership and permissions govern application access. Only enter information you are authorised to use and share it with appropriate users. Review staff access when roles change. This website does not create accounts or grant access to company records.'],
 ['Beta access, plans and subscriptions','O-IBS is preparing for early access / closed beta. Approved monthly prices are Basic R190/month, Business R450/month and Complete R650/month. O-IBS is not currently registered for VAT; no VAT is presently charged. Paid subscriptions are not open here. Applying for early access does not create an account or subscription; applications will be reviewed before invitations. Access conditions, cancellation and refund rules require separate approval. No annual pricing, fees or usage limits are offered in this draft.'],
 ['Acceptable use','Use the service for lawful business purposes. Do not attempt unauthorised access, misuse another organisation’s information, introduce malicious files or use the service for unlawful content. Final enforcement, investigation and suspension procedures require legal and operational approval.'],
 ['Customer data and intellectual property','Customers need appropriate authority to enter and use business data and other people’s information. O-IBS branding and software are distinct from customer records. The final agreement must settle ownership, licences needed to provide the service, confidentiality, permitted processing and data-return arrangements without assuming an unreviewed allocation of rights.'],
 ['Third-party services','Hosting, storage, communications and AI providers may support enabled features. Their availability and terms can affect those features. Approved responsibilities and how material provider changes are handled must be specified in the final agreement.'],
 ['Bizzy and AI limitations','Bizzy helps find information, interpret requests and prepare work. AI may misunderstand requests or documents. Check customers, amounts, products and source records. Important financial changes require the existing approval workflow. Recording a payment does not initiate a bank payment.'],
 ['Business, accounting and tax information','Reports and prepared records depend on information and settings entered. They do not guarantee correct tax treatment, filing compliance or professional advice. Review accounting and tax decisions with an appropriately qualified adviser. Final responsibilities and legally permissible limits require review.'],
 ['Availability and maintenance','Features depend on plans, workspace configuration and service providers. This draft makes no uptime or support-response guarantee. The final agreement must cover maintenance, material changes, support and any agreed availability commitments.'],
 ['Suspension, termination and records','The final terms must address when access may be restricted or ended, notice requirements, remedies and handling of records, exports, backups and outstanding obligations. No automatic deletion timetable or unsupported export entitlement is promised.'],
 ['Liability and disputes','Limits of liability, warranties, exclusions and dispute procedures require professional review and must respect applicable law. No monetary cap or blanket waiver is inserted in this draft.'],
 ['Governing law and jurisdiction','O-IBS is positioned for South African businesses. Counsel must confirm the final South African governing-law and jurisdiction clauses, mandatory protections and dispute routes. This draft does not settle a binding forum clause.']
 ]},
 popia:{title:'POPIA & Privacy',description:'Personal information, business responsibilities and privacy requests in ordinary language.',summary:'POPIA is South Africa’s Protection of Personal Information Act. It concerns handling people’s information for clear reasons, protecting it and respecting applicable rights. Customers and O-IBS each have responsibilities. Company registration is not POPIA certification; this page is not a claim of completed compliance.',sections:[
 ['What POPIA means in practice','Personal information can include names, contact details and information connected to identifiable people or businesses. Customer and supplier documents may contain it. Use only information needed for a clear lawful purpose and give appropriate people access. This overview needs professional confirmation alongside the privacy notice.'],
 ['O-IBS and customer responsibilities','O-IBS handles account and operational information to support its service. Customers choosing which business records to enter also need authority, an appropriate purpose and suitable notices. Precise responsible-party and operator roles, lawful grounds and agreements depend on the processing and must be confirmed by counsel.'],
 ['Access and safeguards','The application checks signed-in access, company membership, permissions and document access. Businesses should protect accounts, manage staff permissions and avoid unnecessary personal details in uploads. These are safeguards, not certification or a guarantee against all incidents.'],
 ['Privacy requests','Access, correction, deletion and objections may be available subject to the law and restrictions. Identity and authority may need checking. An approved Information Officer contact and operational procedure are still required. The online enquiry route, when enabled, can pass questions to O-IBS; it is not a completed formal privacy-request procedure.'],
 ['Cloud and AI processing','Cloud and AI providers may process information for enabled tasks. Some processing may occur internationally. Provider terms, safeguards, operator arrangements and applicable transfer grounds must be reviewed. The AI & Data Use page explains the information AI tasks may involve.'],
 ['Security incidents','A security compromise can involve unauthorised access, loss or disclosure of personal information. Investigation and notification duties need assessment under POPIA. The Information Regulator publishes incident guidance. O-IBS must confirm operational incident responsibilities and reporting processes; this page does not promise an implemented response timetable.'],
 ['Information Officer and PAIA','O-IBS does not currently have a confirmed/registered Information Officer. Officer appointment/registration and privacy governance require owner action. The PAIA status page is the place for the final reviewed access-to-information manual and approved request channel. Neither this overview nor that status page replaces a final manual.']
 ]}
};
export function legalPage(kind,{pageHero,privacyEmail,escape}){const d=drafts[kind];return `${pageHero('Legal / professional review draft',d.title,d.description)}<section class="section"><div class="wrap longcopy">${companyIdentity()}<div class="notice"><strong>${kind==='terms'?'DRAFT — PROFESSIONAL LEGAL REVIEW REQUIRED BEFORE PUBLIC PAID LAUNCH':'DRAFT — requires professional legal review.'}</strong><p>Legal wording, processing arrangements and procedures remain subject to approval. This draft does not establish completed compliance.</p></div><div class="legal-short"><h2>The short version</h2><p>${d.summary}</p></div>${d.sections.map(([title,text])=>`<section><h2>${title}</h2><p>${text}</p></section>`).join('')}<h2>Privacy and legal contact route</h2><p>${privacyEmail?`Privacy enquiries: <a class="text-link" href="mailto:${escape(privacyEmail)}">${escape(privacyEmail)}</a>`:`${supportLink()} is available for general privacy and legal questions. It is not a published Information Officer appointment; formal privacy and PAIA procedures remain to be approved. Website forms cannot submit requests.`}</p><p><a class="text-link" href="/contact">Contact status</a> · <a class="text-link" href="/ai-data">AI &amp; Data Use</a> · <a class="text-link" href="/paia">PAIA status</a></p><p>Official information: <a class="text-link" href="https://inforegulator.org.za/popia/">Information Regulator — POPIA</a> · <a class="text-link" href="https://inforegulator.org.za/paia/">PAIA guides</a> · <a class="text-link" href="https://inforegulator.org.za/complaints/">Complaints</a>.</p><p class="micro">Draft for professional review · 7 October 2026</p></div></section>`;}
