import {companyIdentity,supportLink} from './company.mjs';
export function securityPage(pageHero){return `${pageHero('Security & trust','Bizzy helps.<br>You stay in control.','Access safeguards and approval before important changes, explained in everyday language.')}<section class="section"><div class="wrap"><div class="grid">${[
 ['Authenticated accounts','The application checks signed-in sessions and uses password hashing. Protect your credentials and keep access limited to authorised people.'],
 ['Company-scoped access','Company membership and permissions are checked before access to business records. Businesses should review who has access when staff roles change.'],
 ['Private document access','Stored application documents are served through company and feature-access checks. This marketing website has no business-document uploads or access to your company records.'],
 ['Approval before important changes','Bizzy can prepare work and suggest a next step. Important financial changes are presented for approval; recording a payment does not transfer money.'],
 ['Careful business records','Accounting checks support review of adjustments and records. Review the information entered and consult your bookkeeper or accountant where needed; the software does not guarantee tax compliance.'],
 ['Service credentials stay server-side','The marketing site does not contain application service credentials. Enabled application integrations handle their service credentials on the server rather than publishing them in the website.']
 ].map(([title,copy])=>`<article class="card"><h2 class="feature-title">${title}</h2><p>${copy}</p></article>`).join('')}</div><div class="longcopy"><h2>HTTPS and the public website</h2><p>The public marketing website is served over HTTPS. Website demonstrations use synthetic data and do not connect to AI providers or the application database. When online forms are disabled, entries stay on the page. The prepared marketing form service, when enabled, validates submissions and sends internal emails; it has no application-database integration. No advertising trackers, analytics scripts or third-party fonts are included.</p><h2>What these safeguards mean</h2><p>These descriptions reflect reviewed application controls, not a penetration test, certification or guarantee that incidents cannot happen. Deployed configuration, backups, storage protections, monitoring, provider contracts and incident procedures need separate operational review.</p><h2>Privacy and incidents</h2><p>Questions or concerns can be emailed to ${supportLink()}. Do not email passwords or confidential business records. Formal incident handling and privacy procedures still require operational approval. The website forms cannot deliver an incident report. Read <a class="text-link" href="/privacy">Privacy</a>, <a class="text-link" href="/popia">POPIA &amp; Privacy</a> and <a class="text-link" href="/ai-data">AI &amp; Data Use</a> for information-handling boundaries and matters still requiring professional review.</p>${companyIdentity()}</div></div></section>`;}
