import fs from 'node:fs';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/chant/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const source=fs.readFileSync('src/assets/o-ibs-logo.jpeg');const image='data:image/jpeg;base64,'+source.toString('base64');
const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({deviceScaleFactor:1});
await page.setViewportSize({width:512,height:256});await page.setContent(`<style>html,body{margin:0}img{display:block;width:512px;height:256px}</style><img src="${image}" width="512" height="256">`);await page.locator('img').evaluate(img=>img.decode());await page.screenshot({path:'src/assets/o-ibs-logo-display.jpeg',type:'jpeg',quality:95});
for(const [size,name] of [[32,'favicon-32'],[48,'favicon-48'],[180,'apple-touch-icon'],[192,'icon-192'],[512,'icon-512']]){await page.setViewportSize({width:size,height:size});await page.setContent(`<style>html,body{margin:0;width:100%;height:100%;background:#050e1b}svg{display:block;width:100%;height:100%}</style><svg xmlns="http://www.w3.org/2000/svg" viewBox="200 160 370 370"><image href="${image}" width="1600" height="800"/></svg>`);await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await page.screenshot({path:`src/assets/${name}.png`});}
await page.setViewportSize({width:1200,height:630});await page.setContent(`<style>html,body{margin:0;background:#050e1b}svg{display:block}</style><svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="#050e1b"/><image href="${image}" x="160" y="-10" width="880" height="440"/><text x="600" y="450" fill="#f4f3ef" font-family="Segoe UI,Arial,sans-serif" font-size="42" text-anchor="middle">Intelligent business management.</text><text x="600" y="503" fill="#ddc39a" font-family="Segoe UI,Arial,sans-serif" font-size="25" text-anchor="middle">Built around South African SMEs.</text><text x="600" y="563" fill="#afbacb" font-family="Segoe UI,Arial,sans-serif" font-size="21" text-anchor="middle">Sales · purchases · inventory · banking · accounting · reporting</text></svg>`);await page.screenshot({path:'src/assets/social-share.png'});fs.writeFileSync('src/assets/brand-provenance.json',JSON.stringify({authoritativeAsset:'o-ibs-logo.jpeg',sha256:crypto.createHash('sha256').update(source).digest('hex'),method:'Original supplied artwork framed and rendered without repainting or redesigning the mark.',sizes:[32,48,180,192,512],social:[1200,630]},null,2));console.log('Generated five icon sizes and one social image from the authoritative supplied logo.');await browser.close();
