import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/chant/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
fs.mkdirSync('qa',{recursive:true});
const browser=await chromium.launch({headless:true,channel:"msedge"});
const page=await browser.newPage();const errors=[],failed=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});page.on('requestfailed',req=>failed.push(req.url()));
const report={widths:[],routes:[],checks:{},errors,failedRequests:failed};
for(const width of [1920,1440,1024,768,430,390,360]){await page.setViewportSize({width,height:1000});await page.goto('http://127.0.0.1:4173');await page.waitForLoadState('networkidle');const dimensions=await page.evaluate(()=>({width:innerWidth,content:document.documentElement.scrollWidth}));if(dimensions.content>width)throw Error(`Homepage overflows at ${width}`);report.widths.push(dimensions);if(width===1440){await page.screenshot({path:'qa/home-desktop-1440.png',fullPage:true});await page.screenshot({path:'qa/home-desktop-viewport.png'});}if(width===390){await page.screenshot({path:'qa/home-mobile-390.png',fullPage:true});await page.screenshot({path:'qa/home-mobile-viewport.png'});await page.locator('.menu').click();if(!await page.locator('.navlinks').isVisible())throw Error('Mobile menu did not open');await page.keyboard.press('Escape');if(await page.locator('.menu').getAttribute('aria-expanded')!=='false')throw Error('Escape failed');report.checks.mobileNavigation=true;}}
for(const route of ['product','bizzy','features','pricing','about','contact','security','help','privacy','terms','popia']){await page.setViewportSize({width:1440,height:1000});const response=await page.goto('http://127.0.0.1:4173/'+route);if(response.status()!==200)throw Error(`Route failed: ${route}`);if(await page.locator('h1').count()!==1)throw Error(`Heading failed: ${route}`);for(const width of [1920,1440,1024,768,430,390,360]){await page.setViewportSize({width,height:1000});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error(`${route} overflows at ${width}`);}report.routes.push(route);await page.setViewportSize({width:1440,height:1000});if(['product','bizzy','features','pricing'].includes(route))await page.screenshot({path:`qa/${route}-desktop.png`,fullPage:true});}
await page.goto('http://127.0.0.1:4173/bizzy');for(const prompt of ['attention','sales','stock','reminder','owed']){await page.locator(`[data-prompt="${prompt}"]`).click();if(await page.locator(`[data-prompt="${prompt}"]`).getAttribute('aria-pressed')!=='true')throw Error('Bizzy selection failed');}report.checks.bizzyExamples=true;await page.locator('[data-prompt="reminder"]').click();if(!await page.locator('.answer-closing').innerText().then(t=>t.includes('No message has been sent')))throw Error('Reminder safety missing');
await page.goto('http://127.0.0.1:4173/contact');if(!await page.locator('button[type="submit"]').isDisabled())throw Error('Contact submissions enabled');report.checks.contactDisabled=true;
await page.goto('http://127.0.0.1:4173');await page.locator('footer').screenshot({path:'qa/footer-desktop.png'});await page.locator('#bizzy').screenshot({path:'qa/bizzy-section.png'});
report.checks.accessibilityBasics=await page.evaluate(()=>{const links=[...document.querySelectorAll('a')];const inputs=[...document.querySelectorAll('input,textarea,select')];return {unnamedLinks:links.filter(a=>!((a.textContent||'').trim()||a.getAttribute('aria-label')||a.querySelector('img[alt]'))).length,unlabelledFields:inputs.filter(i=>!document.querySelector('label[for="'+i.id+'"]')).length,mainLandmarks:document.querySelectorAll('main').length,skipLink:!!document.querySelector('a[href="#main"]')};});if(report.checks.accessibilityBasics.unnamedLinks||report.checks.accessibilityBasics.unlabelledFields)throw Error('Accessibility naming failed');
report.checks.images=await page.locator('img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0&&i.alt));if(!report.checks.images)throw Error('Broken or unlabelled images');
await page.keyboard.press('Tab');report.checks.keyboardFocus=await page.evaluate(()=>document.activeElement.tagName==='A');
const timing=await page.evaluate(()=>{const n=performance.getEntriesByType('navigation')[0];return {domContentLoadedMs:Math.round(n.domContentLoadedEventEnd),loadMs:Math.round(n.loadEventEnd),transferBytes:performance.getEntriesByType('resource').reduce((s,r)=>s+r.transferSize,0)};});report.localTiming=timing;
await page.emulateMedia({reducedMotion:'reduce'});report.checks.reducedMotion=await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior==='auto');
fs.writeFileSync('qa/browser-report.json',JSON.stringify(report,null,2));await Promise.race([browser.close(),new Promise(resolve=>setTimeout(resolve,10000))]);if(errors.length||failed.length)throw Error('Browser errors: '+JSON.stringify({errors,failed}));console.log('PASS: responsive layouts, 12 routes, mobile menu, Bizzy examples, disabled contact, images, console and reduced motion. Screenshots saved to qa/.');
