import fs from 'node:fs';
import path from 'node:path';
import {homeDashboard} from '../src/home-dashboard.mjs';
import {readConfig} from '../src/config.mjs';
import {contactPage} from '../src/contact-page.mjs';
import {legalPage} from '../src/legal-pages.mjs';
import crypto from 'node:crypto';
import {everydayCapabilities,workflows,accountingGuide,planComparison,trustOverview,aiDataPage} from '../src/plain-language.mjs';
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const config=readConfig();
const {origin,app,trial}=config;
if(process.argv.includes('--production'))for(const value of [origin,app,trial].filter(Boolean))if(new URL(value).protocol!=='https:'||['localhost','127.0.0.1','[::1]'].includes(new URL(value).hostname))throw Error('Production public URLs must use HTTPS and cannot be local');
const trialLabel=trial?'Start Free Trial':'Start Early Access';
const trialHref=escape(trial||'/contact#early-access'),signHref=escape(app||'/help#sign-in');
const brand=(extra='')=>`<span class="brand ${extra}"><img src="/assets/o-ibs-logo.jpeg" alt="O-IBS — Optimised Intelligent Business System" width="1600" height="800"></span>`;
const cta=(label=trialLabel,style='gold')=>`<a class="btn ${style}" href="${trialHref}">${label}</a>`;
const icons=['<rect x="5" y="3" width="20" height="26" rx="2"/><path d="M10 10h10M10 16h10M10 22h6"/>','<path d="M3 10h26v17H3zM7 10V5h18v5M11 16h10"/>','<path d="m16 3 13 7v14l-13 7-13-7V10zM3 10l13 7 13-7M16 17v14"/>','<path d="m3 11 13-8 13 8H3ZM6 14v11M13 14v11M20 14v11M27 14v11M3 29h26"/>','<path d="M5 3h22v26H5zM10 8h12M10 14h3M19 14h3M10 20h3M19 20h3M10 25h12"/>','<path d="M4 29V17h5v12M14 29V10h5v19M24 29V3h5v26"/>','<path d="M8 3h12l7 7v19H8zM20 3v8h7M13 17h9M13 23h9"/>','<path d="M6 3h20v26H6zM11 9h10M11 15h10M11 21h5M22 20l3 3 5-6"/>'];
const icon=i=>`<div class="icon" aria-hidden="true"><svg viewBox="0 0 32 34">${icons[i%icons.length]}</svg></div>`;
const features=[
 ['Sell','From the first quote to the final payment. Keep your customer relationships and sales paperwork together.',['Quotes','Invoices','Customer accounts','Statements','Credit notes','Returns','Payments']],
 ['Buy','Know what you have ordered, received and owe. Keep supplier workflows connected.',['Suppliers','Purchase orders','Goods received','Supplier bills','Supplier payments']],
 ['Stock','See what is on hand, what is reserved and what is available to sell.',['Products','Stock on hand','Reserved and available stock','Stock movements','Reorder information','Inventory valuation']],
 ['Banking','Turn statement transactions into a clear, reviewed picture of your money.',['Import or manually record transactions','Review suggested matches','Confirm how transactions fit your records','Bank rules where enabled']],
 ['Accounting','Bring everyday business activity into a connected accounting picture.',['Organise accounting categories','Explore detailed accounting records','Check that accounting entries balance','See income, costs and profit','See what the business owns and owes','Review VAT records','Record accounting adjustments']],
 ['Reports','Understand sales, expenses and stock without piecing together separate spreadsheets.',['See income, costs and profit','Review sales and expenses','Follow customer and supplier accounts','See money owed to you and by you','Review stock and value-added tax (VAT)','Check bank transactions against your records']],
 ['What your business owns (Assets)','Keep asset information organised, with accounting workflows appropriate to the released application.',['Keep a list of business assets','Track their recorded reduction in value over time']],
 ['Documents','Create clear, professional paperwork for your customers and your team.',['Quotes','Invoices','Delivery notes','PDF and Excel support where implemented']],
 ['Requisitions','Use assisted extraction to turn uploaded requisitions into information you can review.',['Extract recognised information','Match recognised products','Review uncertain details','Human review before proceeding']]
];
const featureCards=(detailed=false)=>`<div class="grid">${features.slice(0,detailed?features.length:6).map(([title,description,items],i)=>`<article class="card">${icon(i)}<${detailed?'h2':'h3'} class="feature-title">${title}</${detailed?'h2':'h3'}><p>${description}</p>${detailed?`<ul>${items.map(item=>`<li>${item}</li>`).join('')}</ul>`:''}</article>`).join('')}</div>`;
const values=()=>`<div class="values-strip"><div>${icon(7)}<b>COMPLETE</b><span>Your key operations, connected.</span></div><div>${icon(4)}<b>INTELLIGENT</b><span>Clear answers. Helpful assistance.</span></div><div>${icon(5)}<b>EFFICIENT</b><span>More time for what matters.</span></div><div>${icon(1)}<b>BUILT FOR SMEs</b><span>Designed for South African business.</span></div></div>`;
const bizzy=()=>`<div class="split"><div><div class="eyebrow">A little intelligence. A lot of clarity.</div><h2>Meet Bizzy.<br><span style="color:var(--gold)">Your business assistant.</span></h2><p>You shouldn’t need to search through reports just to understand your business. Ask Bizzy in normal language to find information and prepare your next step.</p><div class="prompt-buttons" aria-label="Explore Bizzy demonstration questions"><button data-prompt="owed" aria-pressed="true">Who owes me money?</button><button data-prompt="attention" aria-pressed="false">What needs my attention today?</button><button data-prompt="sales" aria-pressed="false">How much did I sell this month?</button><button data-prompt="stock" aria-pressed="false">Do I need to reorder any stock?</button><button data-prompt="suppliers" aria-pressed="false">What do I owe suppliers?</button><button data-prompt="quote" aria-pressed="false">Prepare a quote for 4 bearings.</button><button data-prompt="invoice" aria-pressed="false">Show me that invoice.</button><button data-prompt="reminder" aria-pressed="false">Prepare a friendly payment reminder.</button></div><div class="safety">Bizzy helps find information and prepare work. Important financial changes are shown for your approval before they are completed. Payment reminders are drafts for manual sharing.</div></div><div id="bizzy-demo" class="bizzy-box"><div class="chat-heading"><span class="bizzy-avatar" aria-hidden="true">✧</span><div><strong>Bizzy</strong><small>Illustrative conversation · sample data</small></div></div><div class="chat" aria-live="polite" aria-atomic="true"><div class="question">Who owes me money?</div><div class="answer"><span class="answer-text">Three customers have outstanding invoices in this demonstration.</span><table class="chat-table" aria-label="Sample business information"><tbody><tr><td>Demo Customer A</td><td>R 12,450</td></tr><tr><td>Demo Customer B</td><td>R 8,200</td></tr><tr><td>Demo Customer C</td><td>R 4,750</td></tr></tbody></table><p class="answer-closing">I can prepare a friendly payment reminder for you to review.</p><small class="demo-label">No business action has been performed.</small></div></div><div class="chat-prompt">Choose a question to explore the demonstration.</div></div></div>`;
const steps=workflows;
const plans=(heading='h3')=>`<div class="plans">${[
 ['BASIC','Run the essentials','For small businesses that need simple sales, expenses and customer management.',['Keep your customers in one place','Create professional quotes and invoices','Record customer payments','Record and organise business expenses','See simple reports showing how the business is doing','Ask Bizzy everyday business questions']],
 ['BUSINESS','Know where your money stands','For businesses that also buy from suppliers and need a clearer picture of what they owe, what customers owe them and how the business is performing.',['Everything in Basic','See which customers still owe you money','See what you still owe suppliers','Customer statements and credit notes','Keep track of what your business owns (assets)','Match bank transactions to your O-IBS records','See detailed business and accounting reports, with accounting terms explained in everyday language','More advanced help from Bizzy']],
 ['COMPLETE','Run your whole operation','For businesses that buy, hold and sell products or stock.',['Everything in Business','Keep track of products and stock quantities','Create purchase orders for suppliers','Record stock when it arrives','See what stock is available, reserved or running low','See how much your stock is worth','Stock and inventory reports','Record products returned by customers','Bizzy can help answer questions about your stock']]
].map(([name,title,description,items])=>`<article class="plan ${name==='COMPLETE'?'featured':''}"><div class="plan-name">O-IBS ${name}</div><${heading}>${title}</${heading}><div class="soon">Early-access pricing coming soon</div><p>${description}</p><ul>${items.map(t=>`<li>${t}</li>`).join('')}</ul>${cta('Start Early Access',name==='COMPLETE'?'gold':'')}</article>`).join('')}</div><p class="micro" style="margin-top:22px">Plan details are provisional. This guide reflects the current feature groupings; closed-beta availability may differ. Final pricing, access terms and limits will be confirmed before paid subscriptions are offered.</p>`;
const closing=()=>`<section class="section"><div class="wrap"><div class="callout"><div class="eyebrow" style="justify-content:center">A clearer way forward</div><h2>Ready to run your<br>business smarter?</h2><p>Your business. One intelligent system.</p><div class="actions">${cta()}<a class="btn" href="${signHref}">Sign In</a></div>${!trial?'<small class="micro">Preparing for early access / closed beta. Start Early Access opens an enquiry preview; online submission and public registration are not enabled yet.</small>':''}</div></div></section>`;
const pageHero=(label,title,copy)=>`<div class="wrap"><section class="page-hero"><div class="eyebrow">${label}</div><h1>${title}</h1><p>${copy}</p></section></div>`;
const header=route=>`<a class="skip" href="#main">Skip to content</a><header><div class="wrap nav"><a class="wordmark" href="/" aria-label="O-IBS home">${brand()}</a><button class="menu" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" class="navlinks" aria-label="Main navigation">${['Product','Bizzy','Features','Pricing','About','Contact'].map(name=>`<a href="/${name.toLowerCase()}" ${route===name.toLowerCase()?'aria-current="page"':''}>${name}</a>`).join('')}<a class="mobile-action" href="${signHref}">Sign In</a><a class="mobile-action" href="${trialHref}">${trialLabel}</a></nav><div class="nav-actions"><a href="${signHref}">Sign In</a>${cta()}</div></div></header>`;
const footer=()=>`<footer><div class="wrap"><div class="footer-grid"><div class="footer-brand"><a class="wordmark" href="/">${brand()}</a><p>Optimised Intelligent<br>Business System</p><p>Your business.<br>One intelligent system.</p></div>${[['Product',[['Product','/product'],['Features','/features'],['Bizzy','/bizzy'],['Plans','/pricing']]],['Company',[['About','/about'],['Contact','/contact']]],['Support',[['Help / Support','/help'],['Security & Trust','/security'],['Sign in',signHref]]],['Legal',[['Privacy Policy','/privacy'],['Terms','/terms'],['AI & Data Use','/ai-data'],['POPIA / Privacy','/popia']]]].map(([label,links])=>`<nav class="footer-col" aria-label="${label}"><strong>${label}</strong>${links.map(([name,href])=>`<a href="${href}">${name}</a>`).join('')}</nav>`).join('')}</div><div class="footer-bottom"><span>© <span data-year>${new Date().getFullYear()}</span> O-IBS. All rights reserved.</span><span>Designed for business. Built around South Africa.</span></div></div></footer>`;
const home=`<section class="hero"><div class="wrap"><div class="hero-grid"><div><div class="eyebrow">Optimised Intelligent Business System</div><h1>Your business.<br><span>One intelligent system.</span></h1><p class="hero-copy">Run your day-to-day business from one place — quotes, invoices, customers, suppliers, stock, banking and accounting — with Bizzy, your intelligent business assistant.</p><div class="actions">${cta()}<a class="btn" href="#how-it-works">See how O-IBS works</a></div><p class="micro">Preparing for early access / closed beta. Public registration is not open yet.</p><div class="hero-notes"><span>Connected operations</span><span>Built-in AI assistance</span><span>You stay in control</span></div></div>${homeDashboard(brand)}</div>${values()}</div></section><section class="section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Everything has its place</div><h2>Everything you need<br>to run your business.</h2><p>From the quote that starts a sale to the numbers that tell the story, keep your everyday work connected.</p></div><a class="text-link" href="/features">Explore all features</a></div>${everydayCapabilities(icon)}</div></section><section class="section alt" id="bizzy"> <div class="wrap">${bizzy()}</div></section><section class="section" id="how-it-works"><div class="wrap"><div class="eyebrow">How it works</div><h2>From work to paperwork —<br>without the paperwork headache.</h2>${steps()}</div></section>${accountingGuide()}<section class="section alt"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Room for your business to grow</div><h2>The right fit for your next chapter.</h2><p>Start with the essentials. Add deeper financial workflows and stock control as your business needs them.</p></div><a class="text-link" href="/pricing">Compare plans</a></div>${plans()}</div></section><section class="section"><div class="wrap split"><div><div class="eyebrow">South African at heart</div><h2>Made for business<br>in South Africa.</h2><p>Work in South African rand (ZAR). Keep track of value-added tax (VAT) on your sales and purchases, so you and your bookkeeper can review what may be owed to SARS or claimable. Built for owners and small teams running a business in South Africa.</p><a class="text-link" href="/about">The thinking behind O-IBS</a></div><div class="card"><div class="eyebrow">Confidence through control</div><h3>Bizzy helps. You stay in control.</h3><p>Bizzy can find information, explain what is happening and prepare work for you. Important changes that affect your business records are shown to you for approval before they are completed.</p><div class="trust-points"><span>Human confirmation</span><span>Reviewed business records</span></div><a class="text-link" style="display:inline-block;margin-top:24px" href="/security">Read our security overview</a></div></div></section>${trustOverview()}${closing()}`;
const product=`${pageHero('The O-IBS platform','Your whole business.<br>A connected view.','Sales, purchasing, stock, banking and accounting belong together. O-IBS brings everyday operations into one intelligent business management platform.')}<section class="section"><div class="wrap"><div class="product-full">${homeDashboard(brand)}</div><p class="micro center" style="margin-top:24px">Illustrative Demo Company workspace. All figures, customers and activity are synthetic sample data.</p></div></section><section class="section alt"><div class="wrap"><div class="section-head"><div><h2>Follow the work.<br>Keep the context.</h2><p>Create a quote, move to an invoice, manage stock and review payments without losing sight of the business behind the paperwork.</p></div></div>${featureCards()}</div></section><section class="section" id="how-it-works"><div class="wrap"><div class="eyebrow">How it works</div><h2>Follow the everyday work.</h2>${steps()}</div></section>${accountingGuide()}${closing()}`;
const bizzyPage=`${pageHero('Meet Bizzy','Ask naturally.<br>Understand clearly.','Your intelligent business assistant helps turn business information into useful answers and prepared actions. You make the decisions.')}<section class="section"><div class="wrap">${bizzy()}</div></section><section class="section alt"><div class="wrap"><div class="section-head"><div><h2>Helpful at every step.<br>Accountable to you.</h2></div></div><div class="grid"><article class="card">${icon(5)}<h3>Understand the business.</h3><p>Ask about sales, outstanding invoices and stock in everyday language.</p></article><article class="card">${icon(0)}<h3>Prepare the next action.</h3><p>Get help drafting a friendly reminder or preparing a business action for review.</p></article><article class="card">${icon(4)}<h3>Review and confirm.</h3><p>Financial and business-changing actions require confirmation. Review amounts, recipients and details before proceeding.</p></article></div><p class="micro" style="margin-top:25px">AI-assisted information can be uncertain. Check details and source documents before relying on a result.</p></div></section>${closing()}`;
const featuresPage=`${pageHero('Features','Built for the work<br>behind your business.','A connected set of tools for sales, suppliers, stock, money and reporting. Feature availability depends on your plan and the released application.')}<section class="section"><div class="wrap">${featureCards(true)}</div></section><section class="section alt"><div class="wrap split"><div><div class="eyebrow">Requisitions, with a second pair of eyes</div><h2>Less retyping.<br>More careful review.</h2><p>O-IBS can assist with extracting information from uploaded requisitions and matching recognised products. Uncertain descriptions, quantities and matches need human review before you proceed.</p></div><div class="card"><h3>A considered workflow.</h3><ul><li>Upload a requisition.</li><li>Review extracted information.</li><li>Check recognised product matches.</li><li>Resolve uncertain details before taking action.</li></ul></div></div></section>${closing()}`;
const pricingPage=`${pageHero('Plans','A plan for where you are.<br>Room for where you’re going.','Choose the depth your business needs, from everyday invoicing to connected accounting and inventory. Commercial pricing is being prepared.')}<section class="section"><div class="wrap">${plans('h2')}${planComparison()}</div></section><section class="section alt"><div class="wrap split"><div><h2>Not sure where to start?</h2><p>Tell us how your business works. We can help you identify which set of workflows fits your needs.</p><a class="btn" href="/contact">Talk to us</a></div><div><h3>Will final prices appear here?</h3><p>Yes. Published prices, VAT treatment, billing terms, trial duration and any limits will be confirmed before commercial subscriptions are offered.</p><h3>Can I start a trial now?</h3><p>${trial?'Use Start Free Trial to visit the configured application entry point.':'O-IBS is preparing for early access / closed beta. Start Early Access opens an enquiry preview; online submissions and public registration are not enabled yet.'}</p></div></div></section>`;
const about=`${pageHero('About O-IBS','Built for serious business.<br>Designed for everyday people.','O-IBS stands for Optimised Intelligent Business System. Our focus is straightforward: bring business operations and accounting together, with intelligent assistance built in.')}<section class="section"><div class="wrap split"><div><h2>Your time belongs<br>to your business.</h2><p>Business owners and small teams often move between paperwork, spreadsheets and separate tools just to understand where things stand.</p><p>O-IBS is designed to connect that work: sales, purchases, inventory, banking and accounting, with Bizzy to help you ask questions and prepare next steps.</p></div><div class="card"><div class="eyebrow">Our starting point</div><h3>South African SMEs.</h3><p>Owners, bookkeepers, administrators and small finance teams. Wholesalers, distributors, service businesses, parts suppliers and trade businesses.</p><div class="trust-points"><span>South African rand (ZAR)</span><span>Value-added tax (VAT) on sales and purchases</span><span>Connected operations</span></div></div></div></section><section class="section alt"><div class="wrap"><h2>The four ideas behind O-IBS.</h2>${values()}</div></section>${closing()}`;
const contact=contactPage({pageHero,config,escape});
const security=`${pageHero('Security & control','Confidence starts<br>with clear boundaries.','Intelligent assistance should support your decisions. Sensitive business actions need human oversight.')}<section class="section"><div class="wrap"><h2 class="visually-hidden">Business controls</h2><div class="grid"><article class="card">${icon(4)}<h3>Confirmation before action.</h3><p>Bizzy helps prepare actions. Financial and business-changing actions require confirmation before completion.</p></article><article class="card">${icon(0)}<h3>Careful accounting records.</h3><p>Review accounting adjustments and detailed records before confirming changes. Your bookkeeper or accountant can use the professional accounting tools available in your plan.</p></article><article class="card">${icon(7)}<h3>Review uncertain information.</h3><p>AI-assisted extraction and product recognition need human review when details are uncertain.</p></article></div><div class="longcopy"><h2>Application security overview</h2><p>The transactional application is separate from this public website. The current application uses password hashing and checks signed-in sessions, company membership and permissions. Stored documents are accessed through company and feature checks. These are implementation safeguards, not a guarantee that information can never be compromised. Operating configuration, provider arrangements and retention still require review.</p><h2>Your information on this website</h2><p>This website has no advertising trackers, analytics scripts or third-party fonts. The enquiry form is not connected to a submission service. It does not transmit or persist the details you enter.</p><h2>Your data and AI assistance</h2><p>Your business information is yours to manage. Important financial changes require approval; recording a payment does not transfer money. Read <a class="text-link" href="/ai-data">AI &amp; Data Use</a> for the information AI may process, and the <a class="text-link" href="/privacy">Privacy Policy draft</a> for topics still requiring legal review.</p><h2>Before public launch</h2><p>HTTPS, approved contact handling and reviewed privacy information are launch requirements. This local preview is not a security certification or a promise of regulatory compliance.</p></div></div></section>`;
const help=`${pageHero('Help / Getting started','A clear place to begin.','Getting-started guidance is being prepared for the public launch.')}<section class="section"><div class="wrap longcopy"><div class="notice"><strong>Help centre preview</strong><p style="margin:8px 0 0">Detailed guides and approved support contact details will be added before launch.</p></div><h2 id="sign-in">Sign in to your business</h2><p>${app?`<a class="text-link" href="${signHref}">Open the O-IBS application</a>`:'The production application link has not been published here yet. Existing users should use the application address already provided to them.'}</p><h2>Start with your company</h2><p>Check your company details and settings before creating business documents. Review how value-added tax (VAT) applies to your business and check your accounting settings with the person responsible for your accounts.</p><h2>Explore an everyday workflow</h2><p>Start with a customer and a quote. Explore invoices, payments and reporting, then add purchasing and stock workflows available in your plan.</p><h2>Ask Bizzy, then review</h2><p>Ask a business question in natural language. Check the answer and review prepared actions before confirming anything that changes your business records.</p><a class="btn" href="/contact">Contact / early access</a></div></section>`;
const legal=kind=>legalPage(kind,{pageHero,privacyEmail:config.privacyEmail,escape});
const pages={
 'ai-data':['AI & Data Use | O-IBS Bizzy and Document Assistance','Understand when O-IBS may use AI, what request or document information may be processed, and why human review matters.',aiDataPage(pageHero)],
 '':['O-IBS | Intelligent Business Management Software for South African SMEs','Manage invoicing, purchases, inventory, banking, accounting and reporting for South African SMEs, with Bizzy, your AI business assistant.',home],
 product:['The O-IBS Platform | Connected Business Management','Explore connected sales, purchasing, inventory, banking and accounting workflows for South African SMEs.',product],
 bizzy:['Bizzy | O-IBS Intelligent Business Assistant','Meet Bizzy: ask natural business questions and prepare actions with human review and confirmation.',bizzyPage],
 features:['O-IBS Features | Sales, Stock, Banking & Accounting','Explore O-IBS tools for quotes, invoices, suppliers, stock, banking, VAT workflows, reports and requisitions.',featuresPage],
 pricing:['O-IBS Plans | Basic, Business & Complete','Compare provisional O-IBS Basic, Business and Complete workflows. Early-access pricing coming soon; paid subscriptions are not open.',pricingPage],
 about:['About O-IBS | Built for South African SMEs','Learn about Optimised Intelligent Business System: complete, intelligent and efficient business tools for South African SMEs.',about],
 contact:['Contact O-IBS | Product & Early Access Enquiries','Explore O-IBS early access and product enquiries. Online contact submissions are being prepared.',contact],
 security:['O-IBS Security Overview | Confirmation & Control','Read about human confirmation, accounting integrity and security information being prepared for public launch.',security],
 help:['O-IBS Help | Getting Started','Getting-started guidance, sign-in information and business workflow orientation for O-IBS.',help],
 privacy:['Privacy Policy Draft | O-IBS','O-IBS privacy policy draft, awaiting professional legal review and approved organisation details.',legal('privacy')],
 terms:['Terms of Service Draft | O-IBS','O-IBS terms of service draft, awaiting professional legal review and commercial terms.',legal('terms')],
 popia:['POPIA Information Draft | O-IBS','Draft South African privacy information for O-IBS, requiring professional legal review before publication.',legal('popia')]
};
fs.mkdirSync('dist/assets',{recursive:true});for(const file of ['site.css','site.js','product-reference.css','home-dashboard.css','readiness.css','content.css','contact.js','contact-contract.mjs'])fs.copyFileSync('src/'+file,'dist/assets/'+file);
fs.copyFileSync('src/assets/o-ibs-logo-display.jpeg','dist/assets/o-ibs-logo.jpeg');
const obsolete='dist/assets/o-ibs-dashboard-reference.jpeg';if(fs.existsSync(obsolete))fs.unlinkSync(obsolete);
for(const file of ['favicon-32.png','favicon-48.png','apple-touch-icon.png','icon-192.png','icon-512.png','social-share.png'])fs.copyFileSync('src/assets/'+file,'dist/assets/'+file);
fs.writeFileSync('dist/site.webmanifest',JSON.stringify({name:'O-IBS — Optimised Intelligent Business System',short_name:'O-IBS',start_url:'/',scope:'/',display:'browser',theme_color:'#050e1b',background_color:'#050e1b',icons:[{src:'/assets/icon-192.png',sizes:'192x192',type:'image/png'},{src:'/assets/icon-512.png',sizes:'512x512',type:'image/png'}]}));
const favicon='/assets/favicon-32.png';
for(const [route,[title,description,body]] of Object.entries(pages)){const canonical=origin+(route?'/'+route:'/');const dir=path.join('dist',route);fs.mkdirSync(dir,{recursive:true});const schema=JSON.stringify({'@context':'https://schema.org','@type':'WebSite',name:'O-IBS',url:origin,description:pages[''][1]}).replace(/</g,'\\u003c');fs.writeFileSync(path.join(dir,'index.html'),`<!doctype html><html lang="en-ZA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${escape(canonical)}"><meta property="og:type" content="website"><meta property="og:site_name" content="O-IBS"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${escape(canonical)}"><meta name="theme-color" content="#050e1b"><link rel="icon" type="image/png" sizes="32x32" href="${escape(favicon)}"><link rel="icon" type="image/png" sizes="48x48" href="/assets/favicon-48.png"><link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png"><link rel="manifest" href="/site.webmanifest"><meta property="og:image" content="${escape(origin)}/assets/social-share.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="O-IBS — Intelligent business management, built around South African SMEs"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(title)}"><meta name="twitter:description" content="${escape(description)}"><meta name="twitter:image" content="${escape(origin)}/assets/social-share.png"><meta name="twitter:image:alt" content="O-IBS official brand and South African SME positioning"><link rel="stylesheet" href="/assets/site.css"><link rel="stylesheet" href="/assets/product-reference.css">${!route||route==='product'?'<link rel="stylesheet" href="/assets/home-dashboard.css">':''}<link rel="stylesheet" href="/assets/readiness.css"><link rel="stylesheet" href="/assets/content.css">${route==='contact'?'<script type="module" src="/assets/contact.js"></script>':''}<script defer src="/assets/site.js"></script>${route==='privacy'||route==='terms'||route==='popia'?'<meta name="robots" content="noindex,follow">':''}${!route?`<script type="application/ld+json">${schema}</script>`:''}</head><body>${header(route)}<main id="main">${body}</main>${footer()}</body></html>`);}
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.keys(pages).filter(r=>!['privacy','terms','popia'].includes(r)).map(route=>`<url><loc>${escape(origin+(route?'/'+route:'/'))}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
for(const [status,title,copy] of [[404,'This page could not be found.','Check the address or return to the homepage to explore O-IBS.'],[500,'Something went wrong.','Please try again later. No internal error details are shown here.']]){fs.writeFileSync('dist/'+status+'.html',`<!doctype html><html lang="en-ZA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><title>${status} | O-IBS</title><link rel="icon" href="/assets/favicon-32.png"><link rel="stylesheet" href="/assets/site.css"><link rel="stylesheet" href="/assets/product-reference.css"><link rel="stylesheet" href="/assets/readiness.css"><script defer src="/assets/site.js"></script></head><body>${header('')}<main id="main" class="error-content">${pageHero(String(status),title,copy)}<div class="wrap"><div class="actions"><a class="btn gold" href="/">Go to homepage</a><a class="btn" href="/contact">Contact</a></div></div></main>${footer()}</body></html>`);}
const schemaContent=JSON.stringify({'@context':'https://schema.org','@type':'WebSite',name:'O-IBS',url:origin,description:pages[''][1]}).replace(/</g,'\\u003c');
const csp="default-src 'self'; script-src 'self' 'sha256-"+crypto.createHash('sha256').update(schemaContent).digest('base64')+"'; style-src 'self' 'unsafe-inline'; img-src 'self'; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'";
const headers={'Content-Security-Policy':csp,'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=(), payment=()','Strict-Transport-Security':'max-age=31536000'};
fs.writeFileSync('dist/_headers','/*\n'+Object.entries(headers).map(([key,value])=>'  '+key+': '+value).join('\n')+'\n');
fs.writeFileSync('qa/security-headers.json',JSON.stringify(headers,null,2));
fs.writeFileSync('qa/release-readiness.json',JSON.stringify({productionExport:process.argv.includes('--production'),releaseReady:false,issues:config.releaseIssues,trialReady:config.trialReady,contactEnabled:config.contactEnabled,externalApplicationRequestsMade:false},null,2));

console.log(`Built ${Object.keys(pages).length} static routes. No application services or databases connected.`);
