import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/chant/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const axeSource=fs.readFileSync('.qa-tools/node_modules/axe-core/axe.min.js','utf8');
const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext();const page=await context.newPage();
const errors=[],failures=[],unexpected=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/404/.test(m.text()))errors.push(m.text());});page.on('requestfailed',r=>failures.push(r.url()));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4173/'))unexpected.push(r.url());});
const routes=['','product','bizzy','features','pricing','about','contact','security','help','ai-data','privacy','terms','popia','paia','early-access','faq'];
const widths=[1920,1440,1024,768,430,390,360];
const report={routes:[],responsive:[],accessibility:[],interactions:{},errors,failedRequests:failures,unexpectedRequests:unexpected};
for(const route of routes){await page.setViewportSize({width:1440,height:1000});const response=await page.goto('http://127.0.0.1:4173/'+route);assert.equal(response.status(),200);assert(response.headers()['content-security-policy']);await page.waitForLoadState('networkidle');assert.equal(await page.locator('h1').count(),1);for(const width of widths){await page.setViewportSize({width,height:1000});const size=await page.evaluate(()=>({viewport:innerWidth,content:document.documentElement.scrollWidth}));assert.equal(size.viewport,size.content,`${route||'home'} overflow at ${width}`);report.responsive.push({route:route||'/',width,overflow:false});}report.routes.push(route||'/');await page.setViewportSize({width:1440,height:1000});await page.evaluate(axeSource);const desktop=await page.evaluate(async()=>window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','best-practice']}}));report.accessibility.push({route:route||'/',width:1440,violations:desktop.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),incomplete:desktop.incomplete.map(v=>v.id)});await page.setViewportSize({width:390,height:1000});const mobile=await page.evaluate(async()=>window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','best-practice']}}));report.accessibility.push({route:route||'/',width:390,violations:mobile.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),incomplete:mobile.incomplete.map(v=>v.id)});}
await page.setViewportSize({width:390,height:1000});await page.goto('http://127.0.0.1:4173/');await page.locator('.menu').click();assert.equal(await page.locator('.menu').getAttribute('aria-expanded'),'true');assert.equal(await page.evaluate(()=>document.activeElement.closest('nav')?.id),'navigation');await page.keyboard.press('Escape');assert.equal(await page.locator('.menu').getAttribute('aria-expanded'),'false');assert.equal(await page.evaluate(()=>document.activeElement.className),'menu');report.interactions.menuKeyboard=true;
await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:4173/bizzy');for(const prompt of ['owed','attention','sales','stock','suppliers','quote','invoice','reminder']){await page.locator(`[data-prompt="${prompt}"]`).click();assert.equal(await page.locator(`[data-prompt="${prompt}"]`).getAttribute('aria-pressed'),'true');}assert((await page.locator('.answer-closing').innerText()).includes('No message has been sent'));report.interactions.bizzySamples=true;
await page.goto('http://127.0.0.1:4173/contact');assert.equal(await page.locator('[name="phone"],input[type="tel"]').count(),0);await page.locator('#check-enquiry').click();assert.equal(await page.locator('#name').getAttribute('aria-invalid'),'true');assert((await page.locator('.form-message').innerText()).includes('review'));await page.locator('#name').fill('Fictional Demo Owner');await page.locator('#business').fill('Demo Company');await page.locator('#email').fill('owner@example.invalid');await page.locator('#message').fill('A synthetic product enquiry for local testing only.');await page.locator('#check-enquiry').click();assert((await page.locator('.form-message').innerText()).includes('nothing has been sent or stored'));assert(await page.locator('button[type="submit"]').isDisabled());report.interactions.contactValidationAndUnavailable=true;
await page.goto('http://127.0.0.1:4173/early-access');assert(await page.locator('button[type="submit"]').isDisabled());assert(!(await page.locator('#privacy').isChecked()));await page.locator('#check-application').click();assert.equal(await page.locator('#name').getAttribute('aria-invalid'),'true');await page.locator('#name').fill('Demo Owner');await page.locator('#business').fill('Demo Company');await page.locator('#email').fill('owner@example.invalid');await page.locator('#businessType').fill('Retail');await page.locator('#employees').selectOption('2–5');await page.locator('#plan').selectOption('Complete');await page.locator('#area-4').check();await page.locator('#check-application').click();assert.equal(await page.locator('#privacy').getAttribute('aria-invalid'),'true');await page.locator('#privacy').check();await page.locator('#check-application').click();assert((await page.locator('.form-message').innerText()).includes('nothing has been sent or stored'));report.interactions.applicationPreviewValidationNoSubmission=true;
// Test the future contact response contract entirely in-browser: no real request is sent.
const isolated=await browser.newContext({bypassCSP:true});const formPage=await isolated.newPage();await formPage.goto('http://127.0.0.1:4173/contact');await formPage.evaluate(()=>{const form=document.getElementById('contact-form');form.dataset.enabled='true';form.dataset.endpoint='/api/contact';form.dataset.backend=location.origin;form.querySelector('button[type="submit"]').disabled=false;form.querySelector('button[type="submit"]').textContent='Send enquiry';});await formPage.route('**/api/form-token',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({token:'synthetic-token',noticeVersion:'2026-10-07'})}));let outcome='accepted';await formPage.route('**/api/contact',route=>route.fulfill({status:outcome==='error'?503:200,contentType:'application/json',body:JSON.stringify({accepted:outcome==='accepted',receipt:'a'.repeat(64)})}));
async function fill(){await formPage.locator('#name').fill('Fictional Demo Owner');await formPage.locator('#business').fill('Demo Company');await formPage.locator('#email').fill('owner@example.invalid');await formPage.locator('#message').fill('A synthetic product enquiry for local testing only.');}
await fill();await formPage.locator('button[type="submit"]').click();await formPage.waitForFunction(()=>document.querySelector('.form-message').dataset.state==='success');assert((await formPage.locator('.form-message').innerText()).toLowerCase().includes('delivery may still be pending'));outcome='error';await fill();await formPage.locator('button[type="submit"]').click();await formPage.waitForFunction(()=>document.querySelector('.form-message').dataset.state==='error');assert.equal(await formPage.locator('#name').inputValue(),'Fictional Demo Owner');assert(!(await formPage.locator('button[type="submit"]').isDisabled()));outcome='not-accepted';await formPage.locator('button[type="submit"]').click();await formPage.waitForFunction(()=>document.querySelector('.form-message').dataset.state==='error');report.interactions.contactMockedSuccessFailureRetry=true;await isolated.close();
await page.goto('http://127.0.0.1:4173/');await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');report.interactions.reducedMotion=true;await page.emulateMedia({reducedMotion:'no-preference'});
await page.evaluate(()=>document.documentElement.style.fontSize='200%');await page.setViewportSize({width:390,height:1000});report.textEnlargement={overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)};
// Verify explanations are available by keyboard and tap, including enlarged text.
await page.goto('http://127.0.0.1:4173/');await page.setViewportSize({width:1440,height:1000});
const explanation=page.locator('.meaning').first();await explanation.locator('summary').focus();await page.keyboard.press('Enter');assert(await explanation.evaluate(el=>el.open));assert(await explanation.locator('p').isVisible());await page.keyboard.press('Space');assert(!(await explanation.evaluate(el=>el.open)));
await page.setViewportSize({width:390,height:1000});await explanation.locator('summary').click();assert(await explanation.evaluate(el=>el.open));await explanation.locator('summary').click();report.interactions.explanationsKeyboardAndTap=true;
await page.goto('http://127.0.0.1:4173/pricing');await page.setViewportSize({width:360,height:1000});assert.equal(await page.locator('.plan-comparison caption').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),360);report.interactions.planComparisonMobile=true;
// Final whole-page review previews.
await page.goto('http://127.0.0.1:4173/');for(const width of [1440,390]){await page.setViewportSize({width,height:1000});await page.locator('.plans').locator('..').locator('..').screenshot({path:'qa/phase2-home-pricing-'+width+'.png',style:'header,.skip{visibility:hidden!important}'});}
for(const width of [1440,390]){await page.setViewportSize({width,height:1000});await page.goto('http://127.0.0.1:4173/early-access');await page.screenshot({path:'qa/phase2-early-access-'+width+'.png',fullPage:true});}

await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:4173/');await page.screenshot({path:'qa/phase2-home-1440.png',fullPage:true});await page.screenshot({path:'qa/phase2-hero-1440.png'});await page.setViewportSize({width:390,height:1000});await page.screenshot({path:'qa/phase2-home-390.png',fullPage:true});await page.screenshot({path:'qa/phase2-hero-390.png'});await page.setViewportSize({width:1440,height:1000});await page.locator('#bizzy').screenshot({path:'qa/phase2-bizzy.png'});await page.locator('footer').screenshot({path:'qa/phase2-footer.png',style:'header,.skip{visibility:hidden!important}'});
for(const [route,name] of [['features','features'],['pricing','pricing'],['contact','contact'],['privacy','privacy'],['ai-data','ai-data'],['terms','terms'],['popia','popia'],['security','security'],['paia','paia'],['a-page-that-does-not-exist','404']]){const response=await page.goto('http://127.0.0.1:4173/'+route);assert.equal(response.status(),name==='404'?404:200);if(name==='features')await page.locator('main').screenshot({path:'qa/phase2-features.png'});else await page.screenshot({path:`qa/phase2-${name}.png`,fullPage:true});}
await page.setViewportSize({width:390,height:1000});await page.goto('http://127.0.0.1:4173/contact');await page.screenshot({path:'qa/phase2-contact-390.png',fullPage:true});
await page.goto('http://127.0.0.1:4173/early-access');await page.locator('#name').fill('Demo Owner');await page.locator('#business').fill('Demo Company');await page.locator('#email').fill('owner@example.invalid');await page.locator('#businessType').fill('Retail');await page.locator('#employees').selectOption('2–5');await page.locator('#plan').selectOption('Complete');await page.locator('#area-4').check();await page.locator('#privacy').check();await page.locator('#check-application').click();await page.screenshot({path:'qa/phase2-application-unavailable-390.png',fullPage:true});
const head=await context.request.head('http://127.0.0.1:4173/');assert.equal(head.status(),200);const bad=await context.request.get('http://127.0.0.1:4173/%E0%A4%A');assert.equal(bad.status(),400);const env=await context.request.get('http://127.0.0.1:4173/.env');assert.equal(env.status(),404);const unavailable=await context.request.post('http://127.0.0.1:4173/api/contact',{data:{}});assert.equal(unavailable.status(),503);assert.equal((await unavailable.json()).accepted,false);report.interactions.httpErrorsAndUnavailableService=true;
fs.writeFileSync('qa/phase2-browser.json',JSON.stringify(report,null,2));const violations=report.accessibility.flatMap(r=>r.violations.map(v=>({...v,route:r.route,width:r.width})));console.log(JSON.stringify({responsiveChecks:report.responsive.length,accessibilityViolations:violations,textEnlargement:report.textEnlargement,errors,failures,unexpected},null,2));await browser.close();if(violations.length||errors.length||failures.length||unexpected.length||report.textEnlargement.overflow)process.exitCode=1;
