import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {readConfig} from '../src/config.mjs';
import {validateApplication} from '../src/early-access-contract.mjs';
import {validateEnquiry} from '../src/contact-contract.mjs';
const routes=['','product','bizzy','features','pricing','about','contact','security','help','ai-data','privacy','terms','popia','paia','early-access'];
const titles=new Set(),descriptions=new Set();let links=0;
for(const route of routes){const html=fs.readFileSync(path.join('dist',route,'index.html'),'utf8');assert.equal((html.match(/<h1[ >]/g)||[]).length,1,`${route}: one h1`);assert.match(html,/<html lang="en-ZA">/);assert.match(html,/<main id="main">/);assert.match(html,/<link rel="canonical"/);assert.match(html,/<meta property="og:title"/);const title=html.match(/<title>(.*?)<\/title>/)[1];assert(!titles.has(title),'unique title');titles.add(title);const desc=html.match(/name="description" content="([^"]+)"/)[1];assert(!descriptions.has(desc),'unique description');descriptions.add(desc);if(['privacy','terms','popia'].includes(route)){assert.match(html,/DRAFT —/);assert.match(html,/noindex,follow/);}for(const match of html.matchAll(/(?:href|src)="(\/[^" ]*|#[^" ]*)"/g)){const [href,anchor]=match[1].split('#');const target=href?path.join('dist',href):path.join('dist',route,'index.html');assert(fs.existsSync(target),`${route}: broken path ${match[1]}`);if(anchor){const file=fs.statSync(target).isDirectory()?path.join(target,'index.html'):target;const dest=fs.readFileSync(file,'utf8');assert(dest.includes(`id="${anchor}"`),`${route}: broken anchor ${match[1]}`);}links++;}assert(!html.includes('staging.o-ibs.co.za'),'staging is not public CTA');assert(!/(postgres(?:ql)?:\/\/|sk_live_|AKIA[0-9A-Z]{16}|re_[A-Za-z0-9]{20})/.test(html),'no common secret patterns');}
const contact=fs.readFileSync('dist/contact/index.html','utf8');assert.match(contact,/type="submit" disabled/);for(const field of ['name','business','email','topic','message'])assert(contact.includes(`for="${field}"`));
assert(!contact.includes('name="phone"'));assert(!contact.includes('type="tel"'));
const sitemap=fs.readFileSync('dist/sitemap.xml','utf8');for(const route of routes.filter(r=>!['privacy','terms','popia','paia'].includes(r)))assert(sitemap.includes(`https://o-ibs.co.za/${route}`));assert.match(fs.readFileSync('dist/robots.txt','utf8'),/Sitemap: https:\/\/o-ibs.co.za\/sitemap.xml/);
const js=fs.readFileSync('dist/assets/site.js','utf8');assert(!/fetch\(|XMLHttpRequest|localStorage|sessionStorage/.test(js),'no transmission or persistence in demonstrations');
const defaultConfig=readConfig();assert.equal(defaultConfig.trialReady,false);assert.equal(defaultConfig.contactEnabled,false);assert.match(contact,/data-enabled="false"/);assert.match(fs.readFileSync('dist/index.html','utf8'),/Start Early Access/);
for(const bad of [{PUBLIC_APP_URL:'https://staging.o-ibs.co.za'},{PUBLIC_APP_URL:'javascript:alert(1)'},{PUBLIC_APP_URL:'https://user:password@app.o-ibs.co.za'},{PUBLIC_APP_URL:'https://app.o-ibs.co.za?token=secret'},{PUBLIC_CONTACT_ENDPOINT:'https://unapproved.example/send'},{PUBLIC_CONTACT_ENABLED:'true',PUBLIC_CONTACT_ENDPOINT:''},{PUBLIC_TRIAL_READY:'true',PUBLIC_TRIAL_URL:''},{PUBLIC_SITE_URL:'https://o-ibs.co.za/subpath'}])assert.throws(()=>readConfig(bad));
const ready=readConfig({PUBLIC_APP_URL:'https://app.o-ibs.co.za',PUBLIC_TRIAL_URL:'https://app.o-ibs.co.za/approved-onboarding',PUBLIC_TRIAL_READY:'true'});assert.equal(ready.app,'https://app.o-ibs.co.za');assert.equal(ready.trialReady,true);
const sample={name:'Demo Owner',business:'Demo Company',email:'owner@example.invalid',topic:'Early access / beta',message:'A fictional product question.',website:''};assert(validateEnquiry(sample).valid);assert(!validateEnquiry({...sample,email:'not-an-email'}).valid);assert(!validateEnquiry({...sample,name:'x'.repeat(121)}).valid);assert(!validateEnquiry({...sample,website:'bot-value'}).valid);assert(!validateEnquiry({...sample,message:'\u0000'}).valid);
const application=fs.readFileSync('dist/early-access/index.html','utf8');assert.match(application,/type="submit" disabled/);assert(!/checked[ >]/.test(application));assert.match(application,/does not automatically create an account or paid subscription/);
const applicationSample={name:'Demo Owner',business:'Demo Company',email:'owner@example.invalid',businessType:'Retail',employees:'2–5',plan:'Complete',areas:['Stock/inventory'],privacy:true,message:''};assert(validateApplication(applicationSample).valid);for(const bad of [{privacy:false},{areas:[]},{areas:['Unapproved feature']},{plan:'Premium'},{email:'invalid'},{message:'x'.repeat(1001)}])assert(!validateApplication({...applicationSample,...bad}).valid);
for(const route of ['','pricing','early-access','terms']){const html=fs.readFileSync('dist/'+(route?route+'/':'')+'index.html','utf8');for(const price of [190,450,650])assert(html.includes('R'+price));assert(!/pricing (?:is )?coming soon|VAT inclusive/i.test(html));}
const earlyJS=fs.readFileSync('dist/assets/early-access.js','utf8');assert(!/fetch\(|XMLHttpRequest|localStorage|sessionStorage/.test(earlyJS));
const output=[];function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory())walk(file);else if(/\.(html|js|mjs|css|xml|txt|webmanifest)$/.test(file))output.push([file,fs.readFileSync(file,'utf8')]);}}walk('dist');
for(const [file,text] of output){if(file.endsWith('.html')){assert(!/href="#"|privacy@|legal@|hello@|accounts@|streetAddress|href="tel:/i.test(text));assert(!/pricing (?:is )?coming soon|VAT inclusive/i.test(text));}assert(!/localhost|127\.0\.0\.1|staging\.o-ibs\.co\.za|SP Components|John Doe|ABC Trading/i.test(text),`${file}: private/development content`);assert(!/(?:sk-(?:proj-)?[A-Za-z0-9_-]{20,}|re_[A-Za-z0-9]{20,}|postgres(?:ql)?:\/\/|BEGIN (?:RSA |EC )?PRIVATE KEY|AKIA[A-Z0-9]{16})/.test(text),`${file}: secret pattern`);assert(!/[A-Z0-9._%+-]+@(?!(?:o-ibs\.co\.za|example\.invalid)\b)[A-Z0-9.-]+\.[A-Z]{2,}/i.test(text),`${file}: unapproved email address`);}
assert(!fs.existsSync('dist/assets/o-ibs-dashboard-reference.jpeg'),'obsolete public dashboard removed');for(const size of [32,48,192,512])assert(fs.existsSync(`dist/assets/${size<100?'favicon':'icon'}-${size}.png`));assert(fs.existsSync('dist/assets/social-share.png'));assert(fs.existsSync('dist/500.html'));assert.match(fs.readFileSync('dist/_headers','utf8'),/Content-Security-Policy:.*object-src 'none'/);for(const route of routes){const html=fs.readFileSync(path.join('dist',route,'index.html'),'utf8');assert.match(html,/twitter:card/);assert.match(html,/og:image/);}
// Render does not consume _headers: check the supported Blueprint against the exact generated policy.
const blueprint=JSON.parse(fs.readFileSync('render.yaml','utf8'));assert.deepEqual(Object.keys(blueprint),['services']);assert.equal(blueprint.services.length,1);
const service=blueprint.services[0];assert.equal(service.name,'o-ibs-marketing');assert.equal(service.runtime,'static');assert.equal(service.rootDir,'o-ibs-marketing');assert.equal(service.staticPublishPath,'dist');assert.equal(service.branch,'master');assert.equal(service.buildCommand,'node scripts/build.mjs --production');assert.equal(service.repo,'https://github.com/chantelchapple-dot/o-ibs-marketing');assert(!service.envVars&&!service.domains&&!service.disk,'No secrets, domains or storage in header configuration');
const expectedHeaders=JSON.parse(fs.readFileSync('qa/security-headers.json','utf8'));assert.deepEqual(service.headers,Object.entries(expectedHeaders).map(([name,value])=>({path:'/*',name,value})));
assert.equal(expectedHeaders['Content-Security-Policy'].split(';').map(s=>s.trim()).find(s=>s.startsWith('connect-src ')),"connect-src 'self' https://o-ibs-marketing-forms.onrender.com");assert.equal(expectedHeaders['Strict-Transport-Security'],'max-age=31536000');for(const [name,value] of Object.entries(expectedHeaders))assert(fs.readFileSync('dist/_headers','utf8').includes(name+': '+value));
fs.writeFileSync('qa/phase2-static.json',JSON.stringify({routes:routes.length,localLinksAndAssets:links,publicTextFilesScanned:output.length,secretPatternsFound:0,privateDataPatternsFound:0,defaultContactEnabled:false,defaultTrialReady:false,configurationNegativeCases:8,contactValidationChecks:5,runtimeDependencies:0},null,2));
console.log(`PASS: ${routes.length} routes, ${links} local links/assets, unique SEO metadata, legal drafts, safe CTAs, form labels, sitemap, robots and secret-pattern checks.`);
